### PR TITLE
feat: configurable default status code

### PR DESCRIPTION
**Pull request by enzious**
Addresses issue #2 with a configurable default.

### CODE REVIEW

**Comment by enzious** [comment]
@jayvdb @joaommartins

**Review by jayvdb — APPROVED** [review]
I am happy as long as the default is 500

**Comment by enzious** [comment]
@jayvdb If you guys are going to be using this in production, I can just add you as collaborators

**Comment by jayvdb** [comment]
> ... I can just add you as collaborators

That would be good.  We're in the process of rolling this out across our services, making the error handling code much neater.

**Comment by enzious** [comment]
Done

**Pull request merged**
