### PR TITLE
Changes default response status code to 500 INTERNAL_SERVER_ERROR

### PR DESCRIPTION
**Pull request by joaommartins**
Addresses issue #2 .

### CODE REVIEW

**Review by jayvdb — APPROVED** [review]

**Comment by enzious** [comment]
Oh, just saw this PR outside the PR. I'll apply this later today.

**Comment by enzious** [comment]
What if I provided an `Option<StatusCode>` for your transform?

**Comment by jayvdb** [comment]
Not sure what you mean by that, but I am guessing that is additional to the change in this PR.
Anyone wanting to use a non-500 error can use `#[response(status = 200)]` on each error that they want to not be a 500.

**Comment by enzious** [comment]
@jayvdb What I mean is on my personal project, I usually bypass HTTP status codes completely and let my application handle errors using a custom schema based on what is essentially success/failure and then provide a reason for any specific meaning. Each reason is tied to a translation, unless the error is 'internal' where I provide no reason

**Comment by enzious** [comment]
Addressed in #4

**Pull request closed without merging**
